### ISSUE TITLE
Port number

### ISSUE THREAD

**Issue by crivotz** [startclean/Chrome-Extension#1]
Hi,
the port number is cut and is not added to the quick connection
 
Es.
`http://localhost:3000` becomes `http://localhost`

Thanks Mauro

**Comment by rawsh** [comment]
Will fix when I get back. Thank you @crivotz !

**Comment by crivotz** [comment]
Thanks @rawsh! All works properly

**Comment by rawsh** [comment]
@crivotz No problem!
