### ISSUE TITLE
Don't open favorites in new tabs

### ISSUE THREAD

**Issue by shadowfacts** [startclean/Chrome-Extension#6]
Currently, when a favorite item is clicked a new tab is opened with the favorite's URL, leaving behind the new tab page. 

Favorites should be opened in the current tab as the current behavior leaves behind an empty tab. Additionally, this is contrary to Chrome's behavior of opening the clicked top page in the current tab.

**Comment by rawsh** [comment]
By favorites, do you mean the links that you can drag and reorder? I fixed the new tab issue a while ago, it opens in the same tab for me. I'll check the code again.

**Comment by rawsh** [comment]
Ah, I found the issue @shadowfacts. I believe you have the lite version of the extension, the links open in a new tab there. It is fixed on the normal version. Thanks for finding the issue!

**Comment by shadowfacts** [comment]
I'm currently using an unpacked local copy which was cloned from this repository, not the lite version.

**Comment by rawsh** [comment]
@shadowfacts I'll try it, and if it has the issue I will reopen it.

**Comment by rawsh** [comment]
@shadowfacts Try it now, I think it should be fixed. I believe I accidently pushed to this repo from the lite folder.
